modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: [ "HTTP/1.1", "HTTP/2"]
      valid_status_codes: [200]  # List of valid HTTP status codes. Empty list means any status code is valid.
      method: GET